# Generated by Django 5.0.2 on 2024-03-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_group_student_group_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='app.lesson', verbose_name='Уроки'),
        ),
    ]
